export interface ServiceData {
  id: string;
  title: string;
  slug: string;
  description: string;
  category: "assessments" | "therapy" | "guidance" | "programs";
  image: string;
  content: {
    overview: string;
    benefits: string[];
    whatToExpect: string[];
    whoIsItFor: string[];
    duration?: string;
    format?: string;
  };
}

export const services: ServiceData[] = [
  // ============================================================================
  // ASSESSMENTS
  // ============================================================================
  {
    id: "1",
    title: "Psychometric Assessments",
    slug: "psychometric-assessments",
    description: "Our psychometric assessments are designed to gently and accurately understand your child's learning style, strengths, and areas where they may need additional support.",
    category: "assessments",
    image: "/features-service-card/child-autism-assessment.png",
    content: {
      overview: "Our psychometric assessments are designed to gently and accurately understand your child's learning style, strengths, and areas where they may need additional support. These assessments help identify cognitive abilities, emotional patterns, and developmental needs to create a clear roadmap for your child's growth.",
      benefits: [
        "Clear understanding of your child's cognitive strengths and challenges",
        "Detailed written report with actionable recommendations",
        "Personalized strategies for home and school",
        "Identification of learning style preferences",
        "Foundation for educational planning and interventions",
      ],
      whatToExpect: [
        "Initial parent consultation to understand concerns and history",
        "2-3 assessment sessions with your child in a child-friendly environment",
        "Standardized testing using age-appropriate tools",
        "Comprehensive written report within 7-10 days",
        "Feedback session to discuss findings and recommendations",
      ],
      whoIsItFor: [
        "Children showing learning difficulties at school",
        "Parents seeking clarity about their child's abilities",
        "Schools requiring formal assessment for support planning",
        "Children being considered for gifted programs",
        "Families wanting to understand developmental delays",
      ],
      duration: "2-3 sessions (60-90 minutes each)",
      format: "In-person at our center",
    },
  },
  {
    id: "2",
    title: "Psychoeducational Assessments",
    slug: "psychoeducational-assessments",
    description: "Psychoeducational assessments play a pivotal role in supporting neurodivergent children — those with learning differences such as ADHD, dyslexia, or autism spectrum disorders.",
    category: "assessments",
    image: "/features-service-card/child-autism-assessment.png",
    content: {
      overview: "Psychoeducational assessments play a pivotal role in supporting neurodivergent children — those with learning differences such as ADHD, dyslexia, or autism spectrum disorders. These comprehensive evaluations examine both cognitive abilities and academic achievement to identify specific learning disabilities and create targeted intervention plans.",
      benefits: [
        "Identification of specific learning disabilities (dyslexia, dyscalculia, dysgraphia)",
        "Detailed academic skill profile across subjects",
        "Customized learning strategies and accommodations",
        "Recommendations for school support and IEP planning",
        "Clear roadmap for academic improvement",
      ],
      whatToExpect: [
        "Review of school records and previous assessments",
        "Parent and teacher questionnaires",
        "Direct assessment of reading, writing, and math skills",
        "Cognitive and achievement testing",
        "Comprehensive report with grade-level comparisons",
      ],
      whoIsItFor: [
        "Children struggling with reading or writing",
        "Students with persistent math difficulties",
        "Children whose grades don't reflect their effort",
        "Students needing school accommodations documentation",
        "Children with suspected ADHD, dyslexia, or autism",
      ],
      duration: "3-4 sessions (60-90 minutes each)",
      format: "In-person at our center",
    },
  },

  // ============================================================================
  // THERAPY
  // ============================================================================
  {
    id: "3",
    title: "Speech Therapy",
    slug: "speech-therapy",
    description: "Communication is one of the most important skills a child develops. When a child struggles to speak clearly, express thoughts, or understand language, it can affect their confidence, learning, and social interactions.",
    category: "therapy",
    image: "/features-service-card/therapy-services.png",
    content: {
      overview: "Communication is one of the most important skills a child develops. When a child struggles to speak clearly, express thoughts, or understand language, it can affect their confidence, learning, and social interactions. Our Speech Therapy services are designed to support children in developing clear communication skills in a structured, engaging, and child-friendly environment. At Divit MindSpace, we help children not just speak — but communicate with confidence.",
      benefits: [
        "Improved speech clarity and articulation",
        "Enhanced vocabulary and language expression",
        "Better social communication skills",
        "Increased confidence in speaking",
        "Parent training for home practice",
      ],
      whatToExpect: [
        "Initial assessment of speech and language skills",
        "Individualized therapy goals and plan",
        "Weekly therapy sessions (play-based for young children)",
        "Regular progress updates and home practice activities",
        "Collaboration with schools when needed",
      ],
      whoIsItFor: [
        "Children with speech delays or unclear speech",
        "Children with language delays or disorders",
        "Children who stutter or have fluency issues",
        "Children with autism needing communication support",
        "Children with hearing impairment affecting speech",
      ],
      duration: "45-minute sessions, typically weekly",
      format: "In-person or online options available",
    },
  },
  {
    id: "4",
    title: "Occupational Therapy",
    slug: "occupational-therapy",
    description: "Every child needs essential daily life skills to grow with confidence and independence. When a child struggles with motor skills, coordination, sensory processing, or routine activities, occupational therapy can help.",
    category: "therapy",
    image: "/features-service-card/therapy-services.png",
    content: {
      overview: "Every child needs essential daily life skills to grow with confidence and independence. When a child struggles with motor skills, coordination, sensory processing, or routine activities, it can impact their ability to participate fully in school and daily life. Our Occupational Therapy services help children develop the skills they need for everyday success through engaging, play-based activities.",
      benefits: [
        "Improved fine motor skills and hand strength",
        "Better sensory regulation and processing",
        "Enhanced handwriting and school readiness",
        "Greater independence in self-care tasks",
        "Improved attention and focus for learning",
      ],
      whatToExpect: [
        "Comprehensive OT evaluation",
        "Sensory profile assessment if needed",
        "Individualized therapy plan with specific goals",
        "Fun, engaging therapy sessions",
        "Home program with activities to practice",
      ],
      whoIsItFor: [
        "Children with sensory processing difficulties",
        "Children struggling with handwriting",
        "Children with fine motor delays",
        "Children needing help with self-care skills",
        "Children with coordination difficulties",
      ],
      duration: "45-minute sessions, typically weekly",
      format: "In-person at our sensory-equipped center",
    },
  },
  {
    id: "5",
    title: "Behavioral Therapy",
    slug: "behavioral-therapy",
    description: "Every child expresses emotions differently. Sometimes, challenging behaviors are not defiance — but a way of communicating unmet needs, frustration, or difficulty coping.",
    category: "therapy",
    image: "/features-service-card/therapy-services.png",
    content: {
      overview: "Every child expresses emotions differently. Sometimes, challenging behaviors are not defiance — but a way of communicating unmet needs, frustration, or difficulty coping. Our Behavioral Therapy program is designed to help children develop positive behaviors, emotional regulation skills, and healthier responses to everyday situations. At Divit MindSpace, we focus on understanding the reason behind the behavior — not just correcting it.",
      benefits: [
        "Reduction in challenging behaviors",
        "Development of emotional regulation skills",
        "Improved impulse control",
        "Better social behaviors and interactions",
        "Parent guidance and training for consistency",
      ],
      whatToExpect: [
        "Identifying triggers and behavioral patterns",
        "Teaching emotional awareness",
        "Building coping mechanisms",
        "Positive reinforcement strategies",
        "Consistent progress monitoring",
      ],
      whoIsItFor: [
        "Children with frequent tantrums or meltdowns",
        "Children struggling with anger management",
        "Children displaying aggressive behavior",
        "Children finding it hard to follow rules",
        "Children diagnosed with ADHD, Autism, or developmental conditions",
      ],
      duration: "45-60 minute sessions",
      format: "In-person, home-based, or center-based",
    },
  },
  {
    id: "6",
    title: "Group Therapy Sessions",
    slug: "group-therapy-sessions",
    description: "Our Group Therapy Sessions are designed to help children develop essential social, emotional, and communication skills in a structured and supportive group setting.",
    category: "therapy",
    image: "/features-service-card/therapy-services.png",
    content: {
      overview: "Our Group Therapy Sessions are designed to help children develop essential social, emotional, and communication skills in a structured and supportive group setting. Children learn best when they interact with peers, and group therapy provides the perfect environment for practicing real-world social skills with guidance from trained therapists.",
      benefits: [
        "Practice social skills with same-age peers",
        "Learn friendship and conversation skills",
        "Build confidence in social situations",
        "Develop perspective-taking abilities",
        "Make genuine peer connections",
      ],
      whatToExpect: [
        "Small groups of 4-6 children",
        "Structured curriculum targeting specific skills",
        "Fun, engaging activities and games",
        "Practice opportunities with peer feedback",
        "Parent updates on skills being learned",
      ],
      whoIsItFor: [
        "Children with autism spectrum disorder",
        "Children struggling to make friends",
        "Children with social anxiety",
        "Children who misread social cues",
        "Children needing peer interaction practice",
      ],
      duration: "60-minute weekly sessions (8-12 week programs)",
      format: "In-person small group at our center",
    },
  },
  {
    id: "12",
    title: "Cognitive Therapy",
    slug: "cognitive-therapy",
    description: "Cognitive therapy helps neurodivergent individuals recognize the connection between thoughts, feelings, and behaviors — building practical coping skills for anxiety, emotional regulation, and daily challenges.",
    category: "therapy",
    image: "/features-service-card/therapy-services.png",
    content: {
      overview: "Cognitive therapy helps neurodivergent individuals understand and reshape the connection between their thoughts, feelings, and behaviors. At Divit MindSpace, we use adapted, neurodiversity-affirming approaches that are concrete, experiential, and tailored to each individual's unique way of processing the world. Our goal isn't to change who you are — it's to help you develop practical skills for managing anxiety, regulating emotions, and navigating daily challenges with confidence.",
      benefits: [
        "Better understanding of thought-feeling-behavior connections",
        "Practical coping strategies for anxiety and stress",
        "Improved emotional regulation skills",
        "Enhanced problem-solving abilities",
        "Greater self-awareness and self-compassion",
      ],
      whatToExpect: [
        "Initial assessment of current challenges and goals",
        "Concrete, visual, and experiential therapeutic techniques",
        "Practical skill-building exercises adapted for neurodivergent minds",
        "Homework activities to practice skills between sessions",
        "Regular progress review and goal adjustment",
      ],
      whoIsItFor: [
        "Children, teens, and adults with anxiety",
        "Individuals with autism seeking coping strategies",
        "Those with ADHD struggling with emotional regulation",
        "Anyone experiencing negative thought patterns",
        "Neurodivergent individuals facing social or daily life challenges",
      ],
      duration: "50-60 minute sessions, typically weekly",
      format: "In-person or online",
    },
  },
  {
    id: "13",
    title: "Play Therapy",
    slug: "play-therapy",
    description: "Play is the natural language of children. Through guided play, neurodivergent children explore emotions, develop social skills, and process experiences in a safe, affirming environment.",
    category: "therapy",
    image: "/features-service-card/therapy-services.png",
    content: {
      overview: "Play is the natural language of all children, regardless of diagnosis or developmental differences. At Divit MindSpace, our Play Therapy services provide a safe, affirming space where neurodivergent children can express thoughts and feelings that may be difficult to put into words. Through child-led play, sand tray therapy, creative arts, and structured activities, children develop emotional regulation, social skills, and self-expression — all while doing what comes naturally: playing.",
      benefits: [
        "Safe expression of difficult emotions through play",
        "Improved emotional regulation and self-awareness",
        "Enhanced social and communication skills",
        "Better processing of sensory experiences",
        "Strengthened parent-child relationships through guided play",
      ],
      whatToExpect: [
        "Child-led, non-directive play sessions",
        "Use of sand tray, art materials, puppets, and sensory toys",
        "Neurodiversity-affirming therapeutic approach",
        "Parent coaching for play-based connection at home",
        "Regular feedback on your child's progress and themes",
      ],
      whoIsItFor: [
        "Children with autism spectrum conditions",
        "Children with ADHD or attention challenges",
        "Children struggling with anxiety or emotional expression",
        "Children who have experienced trauma or transitions",
        "Children with communication or social difficulties",
      ],
      duration: "45-50 minute sessions, typically weekly",
      format: "In-person at our child-friendly therapy room",
    },
  },
  {
    id: "14",
    title: "Sensory Integration Program",
    slug: "sensory-integration-program",
    description: "For individuals who experience the world differently through their senses — helping them process, organize, and respond to sensory input for better daily functioning and comfort.",
    category: "therapy",
    image: "/features-service-card/therapy-services.png",
    content: {
      overview: "Many neurodivergent individuals experience the world differently through their senses — sounds may feel overwhelming, textures uncomfortable, or movement either calming or distressing. Our Sensory Integration Program, led by trained occupational therapists, helps children and adults better process and respond to sensory information. Using specialized equipment in our sensory gym, we work on improving sensory modulation, body awareness, and adaptive responses for better daily functioning.",
      benefits: [
        "Improved ability to process sensory information",
        "Better regulation of sensory seeking or avoiding behaviors",
        "Enhanced focus and attention for learning",
        "Greater comfort in everyday environments",
        "Improved motor coordination and body awareness",
      ],
      whatToExpect: [
        "Comprehensive sensory profile assessment",
        "Individualized sensory diet and intervention plan",
        "Sessions in our sensory gym with specialized equipment",
        "Activities using swings, weighted materials, tactile tools",
        "Home sensory strategies for parents and caregivers",
      ],
      whoIsItFor: [
        "Children and adults with sensory processing differences",
        "Individuals with autism (90-95% experience sensory challenges)",
        "Those with ADHD and sensory sensitivities",
        "Children who are sensory seekers or avoiders",
        "Anyone struggling with sensory overload in daily life",
      ],
      duration: "45-minute sessions, 1-2 times weekly",
      format: "In-person at our sensory-equipped center",
    },
  },
  {
    id: "15",
    title: "Brain Gym",
    slug: "brain-gym",
    description: "Movement-based exercises that integrate brain-body connections — improving focus, coordination, memory, and learning readiness through simple, targeted activities.",
    category: "therapy",
    image: "/features-service-card/therapy-services.png",
    content: {
      overview: "Brain Gym uses 26 specially designed movement exercises that support brain-body integration, helping individuals improve focus, coordination, memory, and learning readiness. Based on Educational Kinesiology principles, these simple activities — including cross-lateral movements, lazy eights, and PACE exercises — help activate both hemispheres of the brain and support primitive reflex integration. At Divit MindSpace, we incorporate Brain Gym as part of a holistic approach to supporting neurodivergent learners.",
      benefits: [
        "Improved focus, concentration, and attention",
        "Better hand-eye coordination and motor skills",
        "Enhanced reading, writing, and learning readiness",
        "Reduced stress and improved emotional regulation",
        "Support for primitive reflex integration",
      ],
      whatToExpect: [
        "Assessment of coordination and learning challenges",
        "Introduction to core Brain Gym movements",
        "PACE exercises for learning readiness",
        "Fun, engaging movement sessions",
        "Take-home exercises for daily practice",
      ],
      whoIsItFor: [
        "Children with learning difficulties or dyslexia",
        "Individuals with ADHD or attention challenges",
        "Those with coordination or motor planning difficulties",
        "Children struggling with reading or writing",
        "Anyone seeking to improve focus through movement",
      ],
      duration: "30-45 minute sessions",
      format: "In-person, individual or small group",
    },
  },

  // ============================================================================
  // GUIDANCE
  // ============================================================================
  {
    id: "7",
    title: "Counselling (Child, Adolescent, Adult & Parent)",
    slug: "counselling",
    description: "Neurodiversity-affirming counselling for every stage of life — supporting children, teenagers, adults, and parents in navigating emotions, relationships, and the unique challenges of neurodivergent experiences.",
    category: "guidance",
    image: "/features-service-card/adult-counseling.png",
    content: {
      overview: "At Divit MindSpace, we offer neurodiversity-affirming counselling services for individuals and families across all life stages. Whether you're a child learning to understand your emotions, a teenager navigating academic and social pressures, an adult managing life's complexities, or a parent seeking support — our trained counsellors provide a safe, confidential space to explore feelings, develop coping strategies, and build emotional resilience. We don't aim to change who you are; we help you thrive as yourself.",
      benefits: [
        "Safe, non-judgmental space to express emotions",
        "Neurodiversity-affirming therapeutic approaches",
        "Improved emotional regulation and coping skills",
        "Better understanding of self and relationships",
        "Support for the entire family system",
      ],
      whatToExpect: [
        "Age-appropriate counselling approaches (play-based for children)",
        "Confidential individual or family sessions",
        "Evidence-based, neurodiversity-affirming techniques",
        "Collaborative goal-setting and progress tracking",
        "Parent coaching and family involvement as needed",
      ],
      whoIsItFor: [
        "Children struggling with emotions, anxiety, or transitions",
        "Teenagers facing academic, social, or identity challenges",
        "Adults managing stress, relationships, or neurodivergent experiences",
        "Parents needing support in raising neurodivergent children",
        "Families seeking to improve communication and connection",
      ],
      duration: "45-60 minute sessions (varies by age)",
      format: "In-person or online",
    },
  },
  {
    id: "8",
    title: "Training Program (Shadow Teacher Training)",
    slug: "training-program-shadow-teacher-training-program",
    description: "We believe every child deserves the right support in mainstream classrooms. Our Shadow Teacher Training Program is a comprehensive certification course designed for educators and caregivers.",
    category: "programs",
    image: "/features-service-card/parent-education.png",
    content: {
      overview: "We believe every child deserves the right support in mainstream classrooms. Our Shadow Teacher Training Program is a comprehensive certification course designed for educators, special educators, and caregivers who want to effectively support neurodivergent children in school settings. This program equips participants with practical skills and strategies for inclusive education.",
      benefits: [
        "Comprehensive understanding of neurodevelopmental conditions",
        "Practical classroom support strategies",
        "Behavior management techniques",
        "Communication and collaboration skills",
        "Certification upon completion",
      ],
      whatToExpect: [
        "Theory sessions on child development and learning differences",
        "Practical workshops with role-play scenarios",
        "Case study discussions",
        "Hands-on training with real-world applications",
        "Assessment and certification",
      ],
      whoIsItFor: [
        "Aspiring shadow teachers",
        "Special educators seeking additional training",
        "Parents wanting to support their child better",
        "School staff working with diverse learners",
        "Caregivers of neurodivergent children",
      ],
      duration: "Multi-day intensive program",
      format: "In-person workshop at our center",
    },
  },

  // ============================================================================
  // PROGRAMS
  // ============================================================================
  {
    id: "9",
    title: "Early Intervention Program",
    slug: "early-intervention-program",
    description: "The early years of a child's life are critical for brain development. When developmental delays or early signs of learning differences are identified and addressed promptly, outcomes improve significantly.",
    category: "programs",
    image: "/about_pic1.png",
    content: {
      overview: "The early years of a child's life are critical for brain development. When developmental delays or early signs of learning differences are identified and addressed promptly, outcomes improve significantly. Our Early Intervention Program provides comprehensive support for young children (0-6 years) showing developmental concerns, helping them build a strong foundation for future learning.",
      benefits: [
        "Early identification of developmental concerns",
        "Improved developmental outcomes",
        "Stronger foundation for future learning",
        "Parent empowerment and training",
        "Coordinated multi-disciplinary support",
      ],
      whatToExpect: [
        "Developmental screening and assessment",
        "Individualized intervention plan",
        "Regular therapy sessions across needed areas",
        "Parent coaching and home strategies",
        "Progress monitoring and plan adjustments",
      ],
      whoIsItFor: [
        "Children aged 0-6 years with developmental delays",
        "Children not meeting age-appropriate milestones",
        "Children showing early signs of autism or ADHD",
        "Premature babies or high-risk infants",
        "Parents concerned about their child's development",
      ],
      duration: "Ongoing program with weekly sessions",
      format: "In-person at our center",
    },
  },
  {
    id: "10",
    title: "Special Education & Remedial Sessions",
    slug: "special-education--remedial-sessions",
    description: "Our Special Education and Remedial Sessions are designed to support children who experience learning difficulties, developmental delays, or academic challenges.",
    category: "programs",
    image: "/about_pic2.png",
    content: {
      overview: "Our Special Education and Remedial Sessions are designed to support children who experience learning difficulties, developmental delays, or academic challenges. Using specialized teaching methods and individualized attention, we help children build academic skills at their own pace while addressing underlying learning differences.",
      benefits: [
        "Individualized education plan (IEP) for each child",
        "Specialized teaching methods and materials",
        "Targeted remediation of academic gaps",
        "Building foundational literacy and numeracy skills",
        "Improved confidence and motivation to learn",
      ],
      whatToExpect: [
        "Initial assessment of learning needs",
        "Development of individualized goals",
        "Regular one-on-one or small group sessions",
        "Use of multi-sensory teaching approaches",
        "Regular progress reports for parents",
      ],
      whoIsItFor: [
        "Children with learning disabilities",
        "Children falling behind in academics",
        "Children with dyslexia, dyscalculia, or dysgraphia",
        "Children needing individualized instruction",
        "Students struggling in mainstream classrooms",
      ],
      duration: "45-60 minute sessions, 2-3 times weekly",
      format: "In-person at our center",
    },
  },
  {
    id: "11",
    title: "School Readiness Program",
    slug: "school-readiness-program",
    description: "Starting school is a major milestone in a child's life. For many children, especially those with developmental or learning challenges, the transition can feel overwhelming.",
    category: "programs",
    image: "/about_pic3.png",
    content: {
      overview: "Starting school is a major milestone in a child's life. For many children, especially those with developmental or learning challenges, the transition can feel overwhelming. Our School Readiness Program prepares children for this important step by building the foundational skills they need to thrive in a classroom environment.",
      benefits: [
        "Smooth transition to formal schooling",
        "Development of pre-academic skills",
        "Improved attention and focus",
        "Better social skills for classroom settings",
        "Increased confidence and independence",
      ],
      whatToExpect: [
        "Assessment of school readiness skills",
        "Structured group sessions simulating classroom environment",
        "Focus on pre-literacy and pre-numeracy skills",
        "Social skills training for peer interactions",
        "Parent guidance for supporting transition at home",
      ],
      whoIsItFor: [
        "Children preparing to start formal school",
        "Children with developmental delays entering school",
        "Children who missed preschool experiences",
        "Children anxious about starting school",
        "Children aged 4-6 years",
      ],
      duration: "6-8 week program with regular sessions",
      format: "In-person small group at our center",
    },
  },
  {
    id: "16",
    title: "Parental Training Program",
    slug: "parental-training-program",
    description: "Parenting a neurodivergent child doesn't come with a guide — we help families build one that works. Evidence-based strategies for understanding your child's unique wiring and needs.",
    category: "programs",
    image: "/features-service-card/parent-education.png",
    content: {
      overview: "Parenting a neurodivergent child is a journey that requires understanding, patience, and the right strategies. Our Parental Training Program empowers parents and caregivers with evidence-based knowledge and practical skills to support their child's unique needs. Through structured sessions, we help you understand your child's wiring, manage challenging behaviors, support emotional regulation, and advocate effectively — so you can parent with confidence, not confusion.",
      benefits: [
        "Deep understanding of your child's neurodivergent profile",
        "Practical behavior management strategies that work",
        "Skills for supporting emotional regulation at home",
        "Improved parent-child communication and connection",
        "Confidence in advocating for your child's needs",
      ],
      whatToExpect: [
        "Group sessions with other parents on similar journeys",
        "One-on-one coaching for personalized guidance",
        "Evidence-based curriculum covering key parenting strategies",
        "Practical tools and resources to use at home",
        "Ongoing support and community connection",
      ],
      whoIsItFor: [
        "Parents of children with autism, ADHD, or learning differences",
        "Caregivers seeking structured parenting strategies",
        "Families navigating a new diagnosis",
        "Parents feeling overwhelmed or isolated",
        "Those wanting to strengthen family dynamics",
      ],
      duration: "6-8 week program with weekly sessions",
      format: "In-person group sessions or individual coaching",
    },
  },
  {
    id: "17",
    title: "ECCE (Early Childhood Care and Education)",
    slug: "ecce-early-childhood-care-and-education",
    description: "Foundational early learning program for children aged 3-6, with specialized support for neurodivergent learners — building school readiness through play-based, developmentally appropriate education.",
    category: "programs",
    image: "/about_pic1.png",
    content: {
      overview: "The early years are the foundation for lifelong learning. Our ECCE program provides developmentally appropriate, play-based education for children aged 3-6, with specialized support for neurodivergent learners. Aligned with the National Education Policy 2020 framework, we focus on foundational literacy, numeracy, social-emotional development, and school readiness — all in a sensory-friendly, inclusive environment that honors each child's unique pace and learning style.",
      benefits: [
        "Strong foundation in early literacy and numeracy",
        "Social-emotional skill development",
        "Sensory-friendly learning environment",
        "Individualized learning plans for each child",
        "Smooth transition to formal schooling",
      ],
      whatToExpect: [
        "Play-based, activity-driven learning approach",
        "Small class sizes with trained educators",
        "Focus on holistic development across all domains",
        "Regular parent communication and involvement",
        "Accommodations for diverse learning needs",
      ],
      whoIsItFor: [
        "Children aged 3-6 years preparing for school",
        "Neurodivergent children needing specialized early education",
        "Children with developmental delays or early intervention needs",
        "Families seeking inclusive preschool options",
        "Children who learn best with individualized attention",
      ],
      duration: "Full academic year program",
      format: "In-person at our center (half-day or full-day options)",
    },
  },
  {
    id: "18",
    title: "Certificate in Special Education",
    slug: "certificate-in-special-education",
    description: "Entry-level professional certification for individuals seeking to support neurodivergent learners — comprehensive training in understanding and supporting diverse learning needs.",
    category: "programs",
    image: "/features-service-card/parent-education.png",
    content: {
      overview: "Our Certificate in Special Education provides foundational training for individuals who want to support neurodivergent learners effectively. This comprehensive program covers neurodevelopmental conditions including autism, ADHD, and learning disabilities, along with practical strategies for classroom support, behavior management, and inclusive education. Whether you're a parent seeking deeper knowledge, an aspiring special educator, or a professional wanting to upskill, this certification equips you with essential skills and understanding.",
      benefits: [
        "Comprehensive understanding of neurodevelopmental conditions",
        "Practical classroom and home support strategies",
        "Behavior management and communication techniques",
        "Foundation for career in special education",
        "Certificate of completion for professional development",
      ],
      whatToExpect: [
        "Theory sessions on autism, ADHD, learning disabilities",
        "Practical workshops and case study discussions",
        "Hands-on training with real-world applications",
        "Assessment and evaluation components",
        "Certificate upon successful completion",
      ],
      whoIsItFor: [
        "Aspiring special educators and shadow teachers",
        "Parents wanting deeper understanding of their child's needs",
        "School staff and mainstream teachers",
        "Caregivers working with neurodivergent individuals",
        "Anyone seeking foundational special education knowledge",
      ],
      duration: "3-6 month program",
      format: "In-person or blended learning",
    },
  },
  {
    id: "19",
    title: "Diploma in Special Education",
    slug: "diploma-in-special-education",
    description: "Comprehensive two-year professional qualification preparing special educators to work with neurodivergent children and adults across educational and therapeutic settings.",
    category: "programs",
    image: "/features-service-card/parent-education.png",
    content: {
      overview: "Our Diploma in Special Education is a comprehensive professional qualification designed to prepare educators for rewarding careers supporting neurodivergent learners. This rigorous program covers intellectual and developmental disabilities (IDD), autism spectrum conditions, specific learning disabilities, and evidence-based intervention strategies. With extensive theory and practical training, graduates are equipped to work in schools, therapy centers, rehabilitation settings, and inclusive education environments.",
      benefits: [
        "Professional qualification recognized in the field",
        "In-depth knowledge of diverse neurodevelopmental conditions",
        "Extensive practical training and hands-on experience",
        "Career opportunities in schools, centers, and NGOs",
        "Skills to create individualized education programs (IEPs)",
      ],
      whatToExpect: [
        "Comprehensive curriculum covering IDD, autism, and learning disabilities",
        "Theory sessions combined with practical placements",
        "Case studies, assessments, and supervised practice",
        "Training in specialized teaching methodologies",
        "Final assessment and diploma certification",
      ],
      whoIsItFor: [
        "10+2 graduates seeking special education careers",
        "Teachers wanting to specialize in inclusive education",
        "Professionals transitioning to special education field",
        "Individuals committed to supporting neurodivergent learners",
        "Those seeking recognized professional qualification",
      ],
      duration: "2-year program (4 semesters)",
      format: "In-person with practical placements",
    },
  },
  {
    id: "20",
    title: "NIOS Support Program",
    slug: "nios-support-program",
    description: "Personalized academic support for neurodivergent learners pursuing education through NIOS — flexible, self-paced learning with accommodations that honor each student's unique needs.",
    category: "programs",
    image: "/about_pic2.png",
    content: {
      overview: "The National Institute of Open Schooling (NIOS) offers a lifeline for neurodivergent learners who thrive outside traditional classroom settings. Our NIOS Support Program provides personalized academic coaching, exam preparation, and advocacy support for students pursuing secondary and senior secondary education through NIOS. We help with subject selection, accommodation documentation, remedial support, and life skills integration — ensuring every student can achieve their academic goals at their own pace.",
      benefits: [
        "Flexible, self-paced academic support",
        "Help navigating NIOS accommodations and exemptions",
        "Personalized tutoring aligned with NIOS curriculum",
        "Exam preparation with appropriate strategies",
        "Integration of life skills alongside academics",
      ],
      whatToExpect: [
        "Individual academic assessment and planning",
        "One-on-one or small group tutoring sessions",
        "Support with accommodation applications and documentation",
        "Subject-specific coaching and exam strategies",
        "Regular progress monitoring and parent updates",
      ],
      whoIsItFor: [
        "Neurodivergent teens and adults pursuing NIOS education",
        "School dropouts seeking alternative education pathways",
        "Students with learning disabilities needing flexible options",
        "Those who struggled in mainstream school settings",
        "Learners requiring self-paced academic support",
      ],
      duration: "Ongoing support aligned with NIOS academic calendar",
      format: "In-person or online tutoring",
    },
  },
  {
    id: "21",
    title: "Summer Camp",
    slug: "summer-camp",
    description: "A structured, fun-filled program where neurodivergent children and teens build confidence, friendships, and life skills through therapeutic recreation and peer connection.",
    category: "programs",
    image: "/about_pic3.png",
    content: {
      overview: "Summer should be a time of growth, connection, and fun — for every child. Our Summer Camp is designed specifically for neurodivergent children and teens, providing a structured yet joyful environment where they can build social skills, make genuine friendships, and develop confidence through therapeutic recreation. With low staff-to-camper ratios, sensory-friendly activities, and trained facilitators, we create a space where neurodivergent kids can truly be themselves while learning essential life skills.",
      benefits: [
        "Social skill development in a supportive peer environment",
        "Genuine friendships with like-minded peers",
        "Confidence building through achievable challenges",
        "Structured fun in a sensory-friendly setting",
        "Skill-building in a non-academic environment",
      ],
      whatToExpect: [
        "Themed daily activities including arts, games, and outdoor fun",
        "Social skills groups integrated into camp activities",
        "Sensory-friendly environment and accommodations",
        "Low staff-to-camper ratios for individualized support",
        "End-of-camp celebration and progress sharing with parents",
      ],
      whoIsItFor: [
        "Children and teens aged 6-16 with autism or ADHD",
        "Neurodivergent kids who struggle in typical camp settings",
        "Children seeking peer connections during summer break",
        "Those who benefit from structured recreational activities",
        "Families wanting summer enrichment with therapeutic value",
      ],
      duration: "2-4 week summer program",
      format: "In-person day camp at our center",
    },
  },
];

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return services.find((service) => service.slug === slug);
}

export function getServicesByCategory(category: string): ServiceData[] {
  if (category === "all") return services;
  return services.filter((service) => service.category === category);
}
